INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Dried oregano', 146, 2000, 1854);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Mozzarella cheese', 42300, 100000, 57700);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Tomato sauce ', 20600, 112500, 91900);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Pizza dough ball (8 pack)', 78650, 100000, 21350);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Chilli pepper', 705, 4000, 3295);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Spicy salami', 3390, 7000, 3610);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Ricotta cheese', 10320, 15000, 4680);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Gorgonzola cheese', 10320, 35000, 24680);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Parmesan cheese', 13850, 25000, 11150);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Caesar dressing', 740, 19000, 18260);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Romain lettuce', 3700, 37500, 33800);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Croutons', 1850, 6250, 4400);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Rotisserie chicken pieces', 4440, 25000, 20560);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Strawberry ice cream', 900, 9000, 8100);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('San Pelligrino 33cl', 4, 120, 116);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Capers', 133, 2000, 1867);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Anchovies', 1850, 2000, 150);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Pistachio ice cream', 600, 9000, 8400);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Chocolate ice cream', 3700, 9000, 5300);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Chocolate brownie', 3225, 5000, 1775);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Chicken wings', 3600, 24000, 20400);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Banoffee pie', 4200, 2400, -1800);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Vanilla ice cream', 800, 9000, 8200);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Coca Cola Regular 1.5l', 10, 120, 110);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Eggplant', 2580, 20000, 17420);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Coca Cola Diet 33cl', 8, 120, 112);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Pepperoni', 6320, 25000, 18680);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Coca Cola Regular 33cl', 14, 120, 106);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Calamari', 1250, 7500, 6250);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Tuna', 1250, 6000, 4750);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Shrimp', 1250, 10000, 8750);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Garlic and parsley butter', 255, 9000, 8745);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Fruit salad', 2850, 10000, 7150);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Perrier 1.5l', 10, 120, 110);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Sprite Regular 1.5l', 11, 120, 109);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Fanta Regular 33cl', 29, 120, 91);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Fanta Regular 1.5l', 6, 120, 114);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('San Pelligrino 1.5l', 9, 120, 111);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Perrier 33cl', 3, 120, 117);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Pineapple', 820, 20000, 19180);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Ham', 1030, 20000, 18970);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Sprite Regular 33cl', 3, 120, 117);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Sprite Diet 33cl', 1, 120, 119);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Fanta Diet 1.5l', 2, 120, 118);
INSERT INTO `query3` (`ing_name`, `ordered_weight`, `total_inv_weight`, `remaining_weight`) VALUES ('Coca Cola Diet 1.5l', 1, 120, 119);
